version: '3.4'

networks:
  dev:
    driver: bridge

services:
  afs:
    image: senpaicq/afsmvc
    depends_on:
      - "afs_db"
    ports:
      - "5009:80"
    build:
      context: .
      dockerfile: AFS/Dockerfile
    environment:
      DB_CONNECTION_STRING: "User ID=rick;Password=Ulvi1234!;Host=afs_db;Port=5432;Database=c137;"
    networks:
      - dev

  afs_db:
    image: postgres:latest
    container_name: multiverse3
    environment:
      - POSTGRES_DB=c137
      - POSTGRES_USER=rick 
      - POSTGRES_PASSWORD=Ulvi1234!
    ports:
      - "5432:5432"
    restart: always
    networks:
      - dev